dotNetShop/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using dotNetShop.Data;
using dotNetShop.Models;
using dotNetShop.Services;

namespace dotNetShop.Controllers
{
    [Authorize(Roles = nameof(Role.Admin))]
    [Authorize(Policy = Settings.PolicyName.Admin)]
    public class ArticleController : Controller
    {
        private const int THUMB_WIDTH = 200;
        private readonly IImageService _imageService;
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;

        public ArticleController(IImageService imageService, IArticleService articleService, ICategoryService categoryService)
        {
            _imageService = imageService;
            _articleService = articleService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var articles = await _articleService.GetAllArticles();

            return View(articles);
        }

        public async Task<IActionResult> Create()
        {
            await PopulateCategories(null);

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,ImagePath,ThumbnailPath,ImageFile,CategoryId")] Article article)
        {
            if (ModelState.IsValid)
            {
                if (article.ImageFile != null)
                {
                    article.ImagePath = _imageService.SaveImage(article.ImageFile);
                    article.ThumbnailPath = _imageService.GenerateThumbnail(article.ImagePath, THUMB_WIDTH);
                }

                article = await _articleService.CreateArticle(article);

                return RedirectToAction(nameof(Index));
            }

            await PopulateCategories(article);
            _articleService.ExtendViewModel(article);

            return View(article);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var article = await _articleService.GetArticle(id.Value);

            if (article == null)
                return NotFound();

            return View(article);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var article = await _articleService.GetArticle(id.Value);

            if (article == null)
                return NotFound();

            await PopulateCategories(article);
            _articleService.ExtendViewModel(article);

            return View(article);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,ImagePath,ThumbnailPath,ImageFile,CategoryId")] Article article)
        {
            if (id != article.Id)
                return NotFound();

            if (!await ArticleExists(article.Id))
                return NotFound();

            if (ModelState.IsValid)
            {                
                if (article.ImageFile != null)
                {
                    DeleteArticleImages(article);

                    article.ImagePath = _imageService.SaveImage(article.ImageFile);
                    article.ThumbnailPath = _imageService.GenerateThumbnail(article.ImagePath, THUMB_WIDTH);
                }

                article = await _articleService.UpdateArticle(article);

                return RedirectToAction(nameof(Index));
            }

            await PopulateCategories(article);
            _articleService.ExtendViewModel(article);

            return View(article);
        }

        private async Task PopulateCategories(Article article)
        {
            ViewBag.Categories = new SelectList(await _categoryService.GetAllCategories(), "Id", "Name", (article != null ? article.CategoryId : null));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var article = await _articleService.GetArticle(id.Value);

            if (article == null)
                return NotFound();

            _articleService.ExtendViewModel(article);

            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var article = await _articleService.GetArticle(id);

            if (article == null)
                return NotFound();

            DeleteArticleImages(article);

            await _articleService.DeleteArticle(id);

            return RedirectToAction(nameof(Index));
        }

        private void DeleteArticleImages(Article article)
        {
            if (!string.IsNullOrEmpty(article.ImagePath))
                _imageService.DeleteImage(article.ImagePath);

            if (!string.IsNullOrEmpty(article.ThumbnailPath))
                _imageService.DeleteImage(article.ThumbnailPath);
        }

        private async Task<bool> ArticleExists(int id)
        {
            var article = await _articleService.GetArticle(id);

            return article != null;
        }
    }
}

dotNetShop/Controllers/CartController.cs
using dotNetShop.Data;
using dotNetShop.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace dotNetShop.Controllers
{
    [Authorize(Policy = Settings.PolicyName.NonAdmin)]
    public class CartController : Controller
    {
        private readonly ShopDbContext _context;
        private readonly ICartService _cartService;

        public CartController(
            ShopDbContext context,
            ICartService cartService)
        {
            _context = context;
            _cartService = cartService;
        }

        public IActionResult Index()
        {
            var cartViewModel = _cartService.GetCartViewModel();

            return View(cartViewModel);
        }

        [HttpGet]
        public IActionResult AddToCart(int articleId)
        {
            var article = _context.Articles.Find(articleId);
            if (article == null)
                return RedirectToAction(nameof(ShopController.Index), "Shop");

            Dictionary<int, int> cartItems = _cartService.GetCartItems();

            if (cartItems.ContainsKey(articleId))
                cartItems[articleId] = cartItems[articleId] + 1;    
            else         
                cartItems.Add(articleId, 1);

            _cartService.SaveCartItems(cartItems);

            return RedirectToAction(nameof(ShopController.List), "Shop", new { categoryId = article.CategoryId });
        }

        [HttpGet]
        public IActionResult UpdateCart(int articleId, int quantity)
        {
            if (quantity <= 0)
                return RemoveFromCart(articleId);

            Dictionary<int, int> cartItems = _cartService.GetCartItems();

            if (cartItems.ContainsKey(articleId))
                cartItems[articleId] = quantity;
            else
                cartItems.Add(articleId, quantity);

            _cartService.SaveCartItems(cartItems);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult RemoveFromCart(int articleId)
        {
            Dictionary<int, int> cartItems = _cartService.GetCartItems();

            cartItems.Remove(articleId);

            _cartService.SaveCartItems(cartItems);

            return RedirectToAction(nameof(Index));
        }
    }
}

dotNetShop/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using dotNetShop.Data;
using dotNetShop.Models;
using dotNetShop.Services;
using Microsoft.AspNetCore.Authorization;

namespace dotNetShop.Controllers
{
    [Authorize(Roles = nameof(Role.Admin))]
    [Authorize(Policy = Settings.PolicyName.Admin)]
    public class CategoryController : Controller
    {
        private readonly IImageService _imageService;
        private readonly IArticleService _articleService;
        private readonly ICategoryService _categoryService;

        public CategoryController(IImageService imageService, IArticleService articleService, ICategoryService categoryService)
        {
            _imageService = imageService;
            _articleService = articleService;
            _categoryService = categoryService;
        }

        public async Task<IActionResult> Index()
        {
            var categories = await _categoryService.GetAllCategories();
            return View(categories);            
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Category category)
        {
            if (ModelState.IsValid)
            {
                category = await _categoryService.CreateCategory(category);

                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _categoryService.GetCategory(id.Value);

            if (category == null)
                return NotFound();

            return View(category);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _categoryService.GetCategory(id.Value);

            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Category category)
        {
            if (id != category.Id)
                return NotFound();

            if (!await CategoryExists(category.Id))
                return NotFound();

            if (ModelState.IsValid)
            {
                category = await _categoryService.UpdateCategory(category);

                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var category = await _categoryService.GetCategory(id.Value);

            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _categoryService.GetCategory(id);

            if (category == null)
                return NotFound();

            var articles = await _articleService.GetArticlesByCategory(id);

            var result = articles.ToList();
            result.ForEach(a => DeleteArticle(a));

            await _categoryService.DeleteCategory(id);

            return RedirectToAction(nameof(Index));
        }

        private void DeleteArticle(Article article)
        {
            if (!string.IsNullOrEmpty(article.ImagePath))
                _imageService.DeleteImage(article.ImagePath);

            if (!string.IsNullOrEmpty(article.ThumbnailPath))
                _imageService.DeleteImage(article.ThumbnailPath);

            _articleService.DeleteArticle(article.Id);
        }

        private async Task<bool> CategoryExists(int id)
        {
            var category = await _categoryService.GetCategory(id);
            return category != null;
        }
    }
}

dotNetShop/Views/Shared/_Layout.cshtml
@using dotNetShop.Data;
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - dotNetShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">dotNetShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User) && User.IsInRole(nameof(Role.Admin)))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Article" asp-action="Index">Articles</a>
                            </li>                       
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li> 
                        }                        
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - dotNetShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>