dotNetShop/Models/Order.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Identity;

namespace dotNetShop.Models
{
    public class Order
    {
        public int Id { get; set; }

        [Required]
        [MaxLength(450)]
        public string UserId { get; set; }

        [Required]
        public int AddressId { get; set; }

        [Required]
        [Display(Name = "Total Order Price")]
        [DataType(DataType.Currency)]
        public double TotalOrderPrice { get; set; }

        [Required]
        public OrderUser User { get; set; }

        [Required]
        public Address Address { get; set; }

        [Required]
        [MaxLength(50)]
        [Display(Name = "Payment Method")]
        public string PaymentMethod { get; set; }

        [Required]
        public ICollection<OrderItem> OrderItems { get; set;}
    }
}

dotNetShop/ViewModels/OrderViewModel.cs
using dotNetShop.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace dotNetShop.ViewModels
{
    public class OrderViewModel
    {
        public CartViewModel Cart { get; set; }

        [Required]
        [MaxLength(200)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(200)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        public Address Address { get; set; }

        [Display(Name = "Payment Method")]
        [Required]
        public PaymentMethod? PaymentMethod { get; set; }

        public SelectList PaymentMethods { get; set; }
    }

    public enum PaymentMethod
    {
        [Display(Name = "Credit Card")]
        CreditCard,
        [Display(Name = "Debit Card")]
        DebitCard,
        [Display(Name = "PayPal")]
        PayPal,
        [Display(Name = "Blik")]
        Blik
    }
}

dotNetShop/Controllers/OrderController.cs
using dotNetShop.Data;
using dotNetShop.Models;
using dotNetShop.Services;
using dotNetShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace dotNetShop.Controllers
{
    [Authorize(Policy = Settings.PolicyName.AuthNonAdmin)]
    public class OrderController : Controller
    {
        private readonly ShopDbContext _context;
        private readonly ICartService _cartService;

        public OrderController(
            ShopDbContext context, 
            ICartService cartService)
        {
            _context = context;
            _cartService = cartService;
        }

        private void PopulateOrderViewModel(OrderViewModel model)
        {
            model.Cart = _cartService.GetCartViewModel();

            var selectListItems = new List<SelectListItem>();
            selectListItems.Add(
                new SelectListItem
                {
                    Text = "Please select a payment method",
                    Value = String.Empty
                });

            Type enumType = typeof(PaymentMethod);

            foreach (PaymentMethod method in Enum.GetValues(typeof(PaymentMethod)))
            {
                selectListItems.Add(
                    new SelectListItem
                    {
                        Text = GetEnumDisplayName(method),
                        Value = method.ToString()
                    });
            }

            model.PaymentMethods = new SelectList(
                selectListItems,
                "Value",
                "Text",
                model.PaymentMethod != null ? model.PaymentMethod.ToString() : "");
        }

        [HttpGet]
        public IActionResult Index()
        {
            if (_cartService.IsCartEmpty())
                return RedirectToAction("Index", "Cart");

            var orderViewModel = new OrderViewModel();
            PopulateOrderViewModel(orderViewModel);
       
            return View(orderViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Confirmation(OrderViewModel orderViewModel)
        {
            PopulateOrderViewModel(orderViewModel);

            if (!ModelState.IsValid)
                return View(nameof(Index), orderViewModel);

            var address = new Address
            {
                AddressLine1 = orderViewModel.Address.AddressLine1,
                AddressLine2 = orderViewModel.Address.AddressLine2,
                City = orderViewModel.Address.City,
                Country = orderViewModel.Address.Country,
                PostalCode = orderViewModel.Address.PostalCode
            };

            OrderUser user = GetUser(orderViewModel);

            var order = new Order
            {
                User = user,
                Address = address,
                TotalOrderPrice = orderViewModel.Cart.TotalCartPrice,
                PaymentMethod = GetEnumDisplayName(orderViewModel.PaymentMethod),
                OrderItems = new List<OrderItem>()
            };

            foreach (var cartItem in orderViewModel.Cart.CartItems)
            {
                var orderItem = new OrderItem
                {
                    Quantity = cartItem.Quantity,
                    TotalPrice = cartItem.TotalPrice,
                    ArticleId = cartItem.Article.Id,
                };

                order.OrderItems.Add(orderItem);
            }

            _context.Orders.Add(order);
            await _context.SaveChangesAsync();

            _cartService.ClearCart();

            return View(order);
        }

        private OrderUser GetUser(OrderViewModel orderViewModel)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var identityUser = _context.Users.First(x => x.Id == userId);
            var user = _context.OrderUsers.FirstOrDefault(x => x.Id == userId);

            if (user == null)
            {
                user = new OrderUser
                {
                    Id = identityUser.Id,
                    User = identityUser
                };
            }

            user.FirstName = orderViewModel.FirstName;
            user.LastName = orderViewModel.LastName;

            return user;
        }

        private string GetEnumDisplayName(Enum value)
        {
            var field = value.GetType().GetField(value.ToString());
            var attribute = (DisplayAttribute)Attribute.GetCustomAttribute(field, typeof(DisplayAttribute));

            return attribute == null ? value.ToString() : attribute.Name;
        }
    }
}

dotNetShop/Controllers/ShopController.cs
using dotNetShop.Data;
using dotNetShop.Services;
using dotNetShop.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace dotNetShop.Controllers
{
    [AllowAnonymous]
    public class ShopController : Controller
    {
        private readonly ShopDbContext _context;
        private readonly IArticleService _articleService;

        public ShopController(ShopDbContext context, IArticleService articleService)
        {
            _context = context;
            _articleService = articleService;
        }

        public IActionResult Index()
        {
            var model = new ShopIndexViewModel();
            model.Categories = new SelectList(_context.Categories, "Id", "Name");

            return View(model);
        }

        private const int COUNT = 5;
        private const int DEFAULT_INDEX = 0;

        [HttpGet]
        public async Task<IActionResult> List(int categoryId)
        {
            if (categoryId <= 0)
                return NotFound();

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == categoryId);

            if (category == null)
                return NotFound();

            ViewBag.CategoryName = category.Name;
            ViewBag.Count = COUNT;

            var articles = await _articleService.GetArticles(categoryId, DEFAULT_INDEX, COUNT);

            return View("LazyLoadingList", articles);
        }

        [HttpGet]
        public async Task<IActionResult> ListPartial(int categoryId, int? index)
        {
            if (categoryId <= 0)
                return NotFound();

            var articles = await _articleService.GetArticles(categoryId, index ?? DEFAULT_INDEX, COUNT);

            // Thread.Sleep(1000); // Just to show the Loading message

            return PartialView("_ArticleListPartial", articles);
        }

        [HttpGet]
        public async Task<IActionResult> LoadNextArticles(int categoryId, int index, int count)
        {
            var articles = await _articleService.GetArticles(categoryId, index, count);

            return PartialView("_ArticleListPartial", articles);
        }
    }
}

dotNetShop/Views/Order/Confirmation.cshtml
@{
    ViewData["Title"] = "Order Confirmation";
}
@model dotNetShop.Models.Order

<h2>Order Confirmation</h2>

<h3>User Info</h3>
<div>
    <p>Username: @Model.User.User.UserName</p>
    <p>First Name: @Model.User.FirstName</p>
    <p>Last Name: @Model.User.LastName</p>
    <p>Email: @Model.User.User.Email</p>
</div>

<h3>Delivery Address</h3>
<div>
    <p>Address Line 1: @Model.Address.AddressLine1</p>
    <p>Address Line 2: @Model.Address.AddressLine2</p>
    <p>City: @Model.Address.City</p>
    <p>Country: @Model.Address.Country</p>
    <p>Postal Code: @Model.Address.PostalCode</p>
</div>

<h3>Payment Method</h3>
<div>
    <p>Payment Method: @Model.PaymentMethod</p>
</div>

<p>
    <a asp-controller="Shop" asp-action="Index">Back to Shop</a>
</p>

dotNetShop/Views/Order/Index.cshtml
@{
    ViewData["Title"] = "Confirm Order";
}
@model dotNetShop.ViewModels.OrderViewModel

<h2>Confirm Order</h2>

@if (Model.Cart.CartItems.Any())
{
    <h3>Order Items</h3>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().Article.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().Article.Name)
                </th>
                <th class="cell-right">
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().Article.Price)
                </th>
                <th class="cell-center">
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().Article.ImagePath)
                </th>
                <th class="cell-right">
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().Quantity)
                </th>
                <th class="cell-right">
                    @Html.DisplayNameFor(model => model.Cart.CartItems.First().TotalPrice)
                </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.Cart.CartItems)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Article.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Article.Name)
                </td>
                <td class="cell-right">
                    @Html.DisplayFor(modelItem => item.Article.Price)
                </td>
                <td class="cell-center">
                    <img src="@item.Article.ResolvedThumbnailFilePath" alt="@item.Article.Name" class="thumbnail" />
                </td>
                <td class="cell-right">
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td class="cell-right">
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
            </tr>
        }
        </tbody>
    </table>

    <div>
        <p>Total Price: @Model.Cart.TotalCartPrice</p>
    </div>
    
    <form asp-controller="Order" asp-action="Confirmation" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <h3>User Info</h3>
        <div>
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="LastName"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <h3>Delivery Address</h3>
        <div>
            <label asp-for="Address.AddressLine1"></label>
            <input asp-for="Address.AddressLine1" class="form-control" />
            <span asp-validation-for="Address.AddressLine1" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address.AddressLine2"></label>
            <input asp-for="Address.AddressLine2" class="form-control" />
        </div>
        <div>
            <label asp-for="Address.City"></label>
            <input asp-for="Address.City" class="form-control" />
            <span asp-validation-for="Address.City" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address.Country"></label>
            <input asp-for="Address.Country" class="form-control" />
            <span asp-validation-for="Address.Country" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Address.PostalCode"></label>
            <input asp-for="Address.PostalCode" class="form-control" />
            <span asp-validation-for="Address.PostalCode" class="text-danger"></span>
        </div>

        <h3>Payment Method</h3>
        <div>
            <label asp-for="PaymentMethod"></label>
            <select asp-for="PaymentMethod" asp-items="Model.PaymentMethods" class="form-control"></select>
            <span asp-validation-for="PaymentMethod" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Confirm Order</button>
    </form>
}
else
{
    <p class="no-items">Your shopping cart is empty.</p>
}

<p>
    <a asp-controller="Shop" asp-action="Index">Back to Shop</a>
</p>